apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: pedro229/flask-app:v4  
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: {{ .Values.envName }}
        - name: MYSQL_HOST
          value: "3306"