apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: pedro229/flask-app:v1  # The Docker image we built earlier
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "dev"  # Set the environment variable here
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - name: 8000-tcp
    port: 8080               
    protocol: TCP
    targetPort: 8080    
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-openshift
spec:
  host: superapp.apps-crc.testing
  tls:
    termination: edge
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: flask-app-service